// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqjyssmakwyldhilakfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxanlzc21ha3d5bGRoaWxha2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3MjM2NjUsImV4cCI6MjA0OTI5OTY2NX0.XWIRrm5jRNpKjyzf6aRhNfLbRl9B_owNj3ROhWSaY8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);